{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name : azure-credentials
type: Opaque
data:
  azure-form-recognizer-api : {{ default "empty" .Values.secrets_values.azure_form_recognizer_api | b64enc | quote }}
  azure-form-recognizer-key: {{ default "empty" .Values.secrets_values.azure_form_recognizer_key | b64enc | quote }}
{{- end }}