{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
data:
  file-storage-external-url: {{ default "" .Values.secrets_values.file_storage_external_url | b64enc | quote }}
  frontend-service-backend-url: {{ default "" .Values.secrets_values.frontend_service_backend_url | b64enc | quote }}
  frontend-service-tables-url: {{ default "" .Values.secrets_values.frontend_service_tables_url | b64enc | quote }}
  frontend-service-corleone-url: {{ default "" .Values.secrets_values.frontend_service_corleone_url | b64enc | quote }}
  frontend-service-ocr-url: {{ default "" .Values.secrets_values.frontend_service_ocr_url | b64enc | quote }}
  frontend-service-keycloak-url: {{ default "" .Values.secrets_values.frontend_service_keycloak_url | b64enc | quote }}
  frontend-service-sentry-dsn: {{ default "" .Values.secrets_values.frontend_service_sentry_dsn | b64enc | quote }}
{{- end }}
