{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: file-storage-database
type: Opaque
data:
  file-storage-database-user: {{ default "file_storage" .Values.secrets_values.file_storage_database_user| b64enc | quote }}
  file-storage-database-password: {{ default (randAlphaNum 10 | quote) .Values.secrets_values.file_storage_database_password | b64enc | quote}}
{{- end }}