{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: file-storage-aws-credentials
type: Opaque
data:
  aws-access-key-id : {{ default "" .Values.secrets_values.aws_access_key_id | b64enc | quote }}
  aws-secret-access-key: {{ default (randAlphaNum 10 | quote) .Values.secrets_values.aws_secret_access_key | b64enc | quote}}
{{- end }}