{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: aaccess-mode
type: Opaque
data:
  access-mode : {{ default "organisation" .Values.secrets_values.access_mode | b64enc | quote}}
{{- end }}