{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-enabled
type: Opaque
data:
  auth-enabled : {{ default "true" .Values.secrets_values.auth_enabled | b64enc | quote}}
{{- end }}