{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: corleone-database
type: Opaque
data:
  user : {{ default "corleone" .Values.secrets_values.corleone_db_user | b64enc | quote}}
  password : {{ default (randAlphaNum 29 | quote) .Values.secrets_values.corleone_db_password | b64enc | quote}}
{{- end }}