{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sentry-dsn-corleone
type: Opaque
data:
  sentry-dsn-corleone : {{ default "" .Values.secrets_values.sentry_dsn_corleone | b64enc | quote}}
{{- end }}