{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-validation-user-secret
type: Opaque
data:
  postgres-validation-user-secret: {{default (randAlphaNum 10) .Values.secrets_values.postgres_validation_user_secret | b64enc | quote}}
{{- end }}