{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sentry-dsn-validation
type: Opaque
data:
  sentry-dsn-validation  : {{ default "" .Values.secrets_values.sentry_dsn_validation  | b64enc | quote }}
{{- end }}