{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-vision-auth-key
type: Opaque
data:
  gcp-vision-auth-key  : {{default (randAlphaNum 10 | quote) .Values.secrets_values.gcp_vision_auth_key | b64enc | quote}}
{{- end }}