{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sentry-dsn-ocr
type: Opaque
data:
  sentry-dsn : {{ default "" .Values.secrets_values.sentry_dsn_ocr  | b64enc | quote }}
{{- end }}