{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: document-sentry-dsn
type: Opaque
data:
  sentry-dsn : {{ default "" .Values.secrets_values.document_sentry_dsn | b64enc | quote}}
{{- end }}