{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: file-storage-external-url
type: Opaque
data:
  file-storage-external-url : {{ default "" .Values.secrets_values.file_storage_external_url | b64enc | quote}}
{{- end }}
