{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sentry-dsn-document-api
type: Opaque
data:
  sentry-dsn-document-api : {{ default (randAlphaNum 29 | quote) .Values.secrets_values.sentry_dsn_document_api | b64enc | quote}}
{{- end }}