{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-password
type: Opaque
data:
  rabbitmq-password : {{ default (randAlphaNum 10 |quote) .Values.secrets_values.rabbitmq_password_secret | b64enc | quote }}
{{- end }}