{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
type: Opaque
data:
  redis-password: {{ default (randAlphaNum 10 | quote) .Values.secrets_values.redis_password_secret | b64enc | quote }}
{{- end }}