apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    {{- include "deps-services.labels" . | nindent 4 }}-rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      {{- include "deps-services.selectorLabels" . | nindent 6 }}-rabbitmq
  template:
    metadata:
      {{- with .Values.rabbitmq.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deps-services.selectorLabels" . | nindent 8 }}-rabbitmq
    spec:
      {{- if .Values.rabbitmq.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.rabbitmq.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-rabbitmq
          image: '{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag | default "latest" }}'
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - name: {{ .Values.rabbitmq.rabbitmq_service.portname }}
              containerPort: {{ .Values.rabbitmq.rabbitmq_service.port }}
              protocol: {{ .Values.rabbitmq.rabbitmq_service.protocol }}
            - name: {{ .Values.rabbitmq.management_service.portname }}
              containerPort: {{ .Values.rabbitmq.management_service.port }}
              protocol: {{ .Values.rabbitmq.management_service.protocol }}
            {{ if .Values.rabbitmq_settings.TLS_ENABLED }}
            - name: {{ .Values.rabbitmq.rabbitmq_tls_service.portname }}
              containerPort: {{ .Values.rabbitmq.rabbitmq_tls_service.port }}
              protocol: {{ .Values.rabbitmq.rabbitmq_tls_service.protocol }}
            - name: {{ .Values.rabbitmq.management_tls_service.portname }}
              containerPort: {{ .Values.rabbitmq.management_tls_service.port }}
              protocol: {{ .Values.rabbitmq.management_tls_service.protocol }}
            {{ end }}
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
                optional: false
          env:
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secrets.rabbitmq_password.secretName }}
                key: rabbitmq-password
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
      {{ if .Values.rabbitmq_settings.TLS_ENABLED }}
          volumeMounts:
          - name: security-certs
            mountPath: {{ .Values.certs_location.certs_default_path }}
            readOnly: true
          - name: rabbitmq-config
            mountPath: /etc/rabbitmq/conf.d
            readOnly: true
      volumes:
      - name: security-certs
        secret:
          secretName: {{ .Values.secrets.security_certs.secretName }}
      - name: rabbitmq-config
        secret:
          secretName: {{ .Values.secrets.rabbitmq_config.secretName }}
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitmq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
