apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  labels:
    {{- include "deps-services.labels" . | nindent 4 }}-rabbitmq
data:
  RABBITMQ_DEFAULT_VHOST: {{ .Values.rabbitmq_settings.RABBITMQ_DEFAULT_VHOST | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq_settings.RABBITMQ_DEFAULT_USER | quote }}
