{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: abbyy-password
type: Opaque
data:
  abbyy-password : {{default (randAlphaNum 10) .Values.secrets_values.abbyy_password | b64enc | quote}}
{{- end }}