{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: celery-backend-url 
type: Opaque
data:
  celery-backend-url: {{ printf "%s%s%s%s%s"  "redis://:" .Values.secrets_values.redis_password_secret "@" .Values.redis_settings.REDIS_HOST ":6379/0" | b64enc | quote   }}
{{- end }}