{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: celery-broker-url
type: Opaque
data:
  celery-broker-url: {{ printf "%s%s%s%s%s%s%s"  "pyamqp://" .Values.rabbitmq_settings.RABBITMQ_DEFAULT_USER ":" .Values.secrets_values.rabbitmq_password_secret "@" .Values.rabbitmq_settings.RABBITMQ_DEFAULT_VHOST ":5672/VHOST" | b64enc | quote   }}
{{- end }}