{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-certs-endpoint
type: Opaque
data:
  keycloak-certs-endpoint: {{ default "" .Values.secrets_values.keycloak_certs_endpoint  | b64enc | quote }}
{{- end }}