{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-host
type: Opaque
data:
  postgres-host: {{ default "postgresql" .Values.secrets_values.postgres_host | b64enc | quote }}
{{- end }}