# Demo environment additional values

rabbitmq:
  resources:
    limits:
      cpu:
      memory:
    requests:
      cpu:
      memory:
  rabbitmq_service:
    nodeport:
      enabled: true
      nodePort: 31672
    type: ClusterIP
    portname: 'rm-cn-prt'
    port: 5672
    protocol: TCP
  management_service:
    nodeport:
      enabled: true
      nodePort: 32672
    port: 15672
    portname: 'rm-svc-prt'
    protocol: TCP

nodeSelector:

affinity: {}

