{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl-certificate
type: Opaque
data:
  nginx-ssl-certificate : {{ default "" .Values.secrets_values.nginx_ssl_certificate | b64enc | quote }}
{{- end }}