{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret-ingress
type: Opaque
data:
  tls-secret-ingress : {{ default (randAlphaNum 10) .Values.secrets_values.tls_secret_ingress | b64enc | quote}}
{{- end }}