{{- if .Values.create_secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: upstream-auth-url
type: Opaque
data:
  upstream-auth-url : {{ default "" .Values.secrets_values.upstream_auth_url | b64enc | quote }}
{{- end }}